### ISSUE TITLE
编译成openwrt可执行文件可行性？

### ISSUE THREAD

**Issue by dongnengyu** [cybozu-go/transocks#11]
打算用在openwrt路由器上面，不知可否

**Comment by xixixihaha** [comment]
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags="-s -w"  github.com/cybozu-go/transocks/...
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install -a -ldflags="-s -w" github.com/cybozu-go/transocks/...

Can be used on X86 openwrt system, change GOARCH for other architecture
