### ISSUE TITLE
Use golang.org/x/sys instead of syscall?

### ISSUE THREAD

**Issue by otariidae** [cybozu-go/transocks#13]
While installing transocks on i686 system, I got the following error:
```
go/src/github.com/cybozu-go/transocks/original_dst_linux.go:14:3: undefined: syscall.SYS_GETSOCKOPT
```

[The official document](https://golang.org/pkg/syscall/) says:
> Deprecated: this package is locked down. Callers should use the corresponding package in the golang.org/x/sys repository instead. That is also where updates required by new systems or versions should be applied. See https://golang.org/s/go1.4-syscall for more information.

I manually replaced syscall with golang.org/x/sys/unix. It worked well.

For better OS support, use `golang.org/x/sys` instead?

**Comment by ymmt2005** [comment]
Thank you for the report!

We should replace it as you described.
Are you willing to make a pull request for it?

**Comment by otariidae** [comment]
Thank you for the quick reply.
I submitted #14. Please take a look.
