### ISSUE TITLE
Authentication Handler

### ISSUE THREAD

**Issue by 06chaynes** [cybozu-go/transocks#3]
This is a beautiful library, thank you. I am building a tool for internal use and your library looks like a perfect place to start. I am trying to figure out how I might integrate authentication on the listening end of things. Do you have any suggestions as to how I could achieve this with transocks?

**Comment by ymmt2005** [comment]
Hi,

Transparent proxies such as transocks can be used _transparently_ from applications.
For this reason, applications usually cannot provide information for authentication to transocks.

So, let me know how do you think your application provide authentication information to transocks?

**Comment by ymmt2005** [comment]
Closing.
